<a href="https://colab.research.google.com/github/melaniesandra/melaniesandra.github.io/blob/master/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_excel('energy_analysis.xlsx')
X = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -2:].values

### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=2))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
20/20 [==============================] - 0s 1ms/step - loss: 334.6654
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 180.4636
Epoch 3/100
20/20 [==============================] - 0s 1ms/step - loss: 149.1558
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 130.2711
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 116.5473
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 101.8724
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 86.0214
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 75.9410
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 65.0825
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 56.7882
Epoch 11/100
20/20 [==============================] - 0s 1ms/step - loss: 52.0192
Epoch 12/100
20/20 [==============================] - 0s 2ms/step - loss: 46.5009
Epoch 13/100
20/20 

### Predicting the results of the Test set

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2), y_test.reshape(len(y_test),2)),1))

[[15.96 17.49 15.18 17.63]
 [ 7.04 10.75 10.32 13.57]
 [28.82 30.37 37.26 34.62]
 [25.5  27.38 16.95 21.16]
 [27.38 29.54 32.26 33.34]
 [29.43 30.81 27.9  34.2 ]
 [27.87 29.98 28.18 30.18]
 [25.83 28.67 28.95 30.34]
 [23.94 27.42 29.07 29.82]
 [26.28 29.26 23.8  24.61]
 [ 9.52 11.72  6.4  11.67]
 [28.94 30.43 42.5  38.35]
 [16.66 18.22 11.22 14.65]
 [28.99 30.79 43.1  39.41]
 [29.91 32.31 41.96 37.7 ]
 [23.9  27.57 26.33 31.06]
 [10.5  13.38 10.7  13.87]
 [29.12 30.31 28.09 34.33]
 [22.51 22.05 14.65 15.38]
 [ 9.76 12.8  12.29 15.4 ]
 [12.98 15.29 12.46 14.38]
 [27.69 30.05 32.71 33.13]
 [ 9.73 12.95 10.77 14.14]
 [28.64 30.44 38.57 43.86]
 [ 6.62  9.73  6.04 11.17]
 [ 9.85 13.01 14.66 17.37]
 [22.42 21.84 13.   14.47]
 [ 7.62 12.4  14.41 16.69]
 [ 9.89 12.36 10.75 14.27]
 [29.57 31.96 39.89 37.54]
 [22.21 22.06 12.74 13.97]
 [16.13 17.42 12.74 16.14]
 [29.04 31.16 41.26 46.44]
 [15.82 16.91 12.77 16.22]
 [27.92 30.35 28.56 29.78]
 [40.63 39.01 35.99 36.07]
 [ 7.   11.39 13.97 16.08]
 