<a href="https://colab.research.google.com/github/melaniesandra/melaniesandra.github.io/blob/master/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [15]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_excel('energy_analysis.xlsx')
X = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -2:].values

### turning numerical values into different columns 

In [0]:
from sklearn.preprocessing import PolynomialFeatures, LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [5])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=2))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [28]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
20/20 [==============================] - 0s 1ms/step - loss: 11164.6953
Epoch 2/100
20/20 [==============================] - 0s 1ms/step - loss: 6753.7480
Epoch 3/100
20/20 [==============================] - 0s 1ms/step - loss: 4289.7139
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 2830.6851
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 1927.0472
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 1332.7795
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 931.2778
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 651.9728
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 457.3958
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 323.0564
Epoch 11/100
20/20 [==============================] - 0s 1ms/step - loss: 233.5463
Epoch 12/100
20/20 [==============================] - 0s 1ms/step - loss: 174.5215
Epoch 

### Predicting the results of the Test set

In [29]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2), y_test.reshape(len(y_test),2)),1))

[[15.02 17.08 15.18 17.63]
 [11.71 13.49 10.32 13.57]
 [28.91 30.95 37.26 34.62]
 [25.55 27.47 16.95 21.16]
 [27.07 28.79 32.26 33.34]
 [28.94 30.81 27.9  34.2 ]
 [27.14 28.86 28.18 30.18]
 [25.33 27.25 28.95 30.34]
 [22.24 24.03 29.07 29.82]
 [25.38 27.3  23.8  24.61]
 [12.14 13.99  6.4  11.67]
 [28.91 30.96 42.5  38.35]
 [15.11 17.18 11.22 14.65]
 [28.88 30.93 43.1  39.41]
 [28.92 30.97 41.96 37.7 ]
 [22.2  24.01 26.33 31.06]
 [12.22 14.08 10.7  13.87]
 [28.93 30.8  28.09 34.33]
 [21.92 24.23 14.65 15.38]
 [12.19 14.05 12.29 15.4 ]
 [12.73 14.68 12.46 14.38]
 [27.08 28.8  32.71 33.13]
 [12.23 14.1  10.77 14.14]
 [28.73 30.77 38.57 43.86]
 [11.63 13.39  6.04 11.17]
 [12.19 14.05 14.66 17.37]
 [21.93 24.24 13.   14.47]
 [11.77 13.56 14.41 16.69]
 [12.17 14.02 10.75 14.27]
 [28.76 30.82 39.89 37.54]
 [21.84 24.16 12.74 13.97]
 [15.08 17.14 12.74 16.14]
 [28.72 30.77 41.26 46.44]
 [15.07 17.12 12.77 16.22]
 [27.11 28.83 28.56 29.78]
 [38.43 44.85 35.99 36.07]
 [11.72 13.5  13.97 16.08]
 